@baseUrl = http://localhost:3000
@json = application/json
@email = userdangcap@example.com
@password = StrongPass123!
@deviceId = chrome-123
@email1 = userdangcap1@example.com
@password1 = StrongPass123!
@deviceId = chrome-123

### ===== BODY MODE (refreshToken trong body) =====

### Register (BODY)
POST {{baseUrl}}/auth/register
Content-Type: {{json}}

{
  "email": "{{email1}}",
  "password": "{{password1}}"
}

### Login (BODY) -> copy accessToken, refreshToken từ response
POST {{baseUrl}}/auth/login
Content-Type: {{json}}

{
  "email": "{{email}}",
  "password": "{{password}}",
  "deviceId": "{{deviceId}}"
}

### Refresh (BODY) -> dán refreshToken vào đây
POST {{baseUrl}}/auth/refresh
Content-Type: {{json}}

{
  "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### Logout (BODY) -> dán refreshToken đã dùng
POST {{baseUrl}}/auth/logout
Content-Type: {{json}}

{
  "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### ===== COOKIE MODE (refreshToken bằng HttpOnly cookie) =====
# Bật cookie jar nếu dùng REST Client (rememberCookiesForSubsequentRequests: true)

### Register (COOKIE)
POST {{baseUrl}}/auth/register
Content-Type: {{json}}

{ "email": "user@example.com", "password": "User@123456" }


### Login (COOKIE) -> server Set-Cookie: rt=...
POST {{baseUrl}}/auth/login
Content-Type: {{json}}
User-Agent: MyBrowser/1.0

{
  "email": "{{email1}}",
  "password": "{{password1}}",
  "deviceId": "{{deviceId}}",
  "deviceFp": "fp-A"
}

### Refresh (COOKIE) -> cookie jar sẽ tự gửi rt; nếu không, tự thêm header Cookie
POST {{baseUrl}}/auth/refresh
Content-Type: {{json}}

{}

### (Nếu KHÔNG bật cookie jar) Refresh thủ công với header Cookie:
POST {{baseUrl}}/auth/refresh
Content-Type: {{json}}
Cookie: rt=PASTE_RT_COOKIE_VALUE
User-Agent: MyBrowser/DIFF

{}

### Logout (COOKIE) -> server clear cookie
POST {{baseUrl}}/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdiI6MSwiaWF0IjoxNzU2NTc0MjA4LCJleHAiOjE3NTY1NzUxMDgsImF1ZCI6ImJvb2tpbmctZmUiLCJpc3MiOiJib29raW5nLWFwaSIsInN1YiI6Ijk5MjQxZTVjLTRjYTQtNDg0YS04MDAyLTU4ZTdlNjc5MTBkYyIsImp0aSI6IjI1ODEwNWIwLWRmNmYtNDMzNi1hNmNjLTA5ZTk0NTE1MGRlMiJ9.oToAWA_2YtPGXC40tpn1BcM7LKcwvRfqt2pLlrlEk9E
Content-Type: {{json}}


{}
